%YAML 1.1
---
name: clang_plugin
version: 0.1
languages:
    - cpp
metrics:
    spin_rate:
        name: Spin Rate
        description: Rate at which a node spins.
        scope: file
        min: 0
    subscribers:
        name: Number of Subscriptions
        description: Number of topics a node subscribes to.
        scope: file
        min: 0
    subscribe_nesting:
        name: Level of Subscription Nesting
        description: Number of levels of control flow wrapping a subscription.
        scope: file
        min: 0
    publishers:
        name: Number of Advertisements
        description: Number of topics a node advertises.
        scope: file
        min: 0
    advertise_nesting:
        name: Level of Advertisement Nesting
        description: Number of levels of control flow wrapping an advertisement.
        scope: file
        min: 0
    active_publishers:
        name: Number of Publications
        description: Number of topics a node publishes to.
        scope: file
        min: 0
    publish_nesting:
        name: Level of Publication Nesting
        description: Number of levels of control flow wrapping a publication.
        scope: file
        min: 0
    service_servers:
        name: Number of Service Servers
        description: Number of services a node hosts.
        scope: file
        min: 0
    advertise_service_nesting:
        name: Level of Service Advertisement Nesting
        description: Number of levels of control flow wrapping a service advertisement.
        scope: file
        min: 0
    service_clients:
        name: Number of Service Clients
        description: Number of services a node uses.
        scope: file
        min: 0
    service_client_nesting:
        name: Level of Service Client Nesting
        description: Number of levels of control flow wrapping a service client.
        scope: file
        min: 0
    queue_size:
        name: Size of Topic Queue
        description: Size given to a topic queue.
        scope: file
        min: 0
    hardcoded_topics:
        name: Number of Hard-coded Topic Names
        description: Number of topics explicitly declared as a string literal.
        scope: file
        min: 0
    hardcoded_services:
        name: Number of Hard-coded Service Names
        description: Number of services explicitly declared as a string literal.
        scope: file
        min: 0
    hardcoded_queue_sizes:
        name: Number of Hard-coded Queue Sizes
        description: Number of queue sizes explicitly declared as an integer literal.
        scope: file
        min: 0
    hardcoded_spin_rates:
        name: Number of Hard-coded Spin Rates
        description: Number of spin rates explicitly declared as an integer literal.
        scope: file
        min: 0
    latching_topics:
        name: Number of Latching Topics
        description: Number of topics advertised with latch as true.
        scope: file
        min: 0
    infinite_queues:
        name: Number of Zero-sized Queues
        description: Number of topic queues with size zero.
        scope: file
        min: 0
    transport_hints:
        name: Number of Uses of Transport Hints
        description: Number of uses of Transport Hints.
        scope: file
        min: 0
    global_resource_names:
        name: Number of Global Names Used
        description: Number of uses of global names (topics, services).
        scope: file
        min: 0
    function_callbacks:
        name: Number of Function Callbacks
        description: Number of bare functions used as callbacks.
        scope: file
        min: 0
    method_callbacks:
        name: Number of Method Callbacks
        description: Number of class member functions used as callbacks.
        scope: file
        min: 0
    boost_callbacks:
        name: Number of Boost Function Callbacks
        description: Number of boost functions used as callbacks.
        scope: file
        min: 0
supported_metrics:
    - spin_rate
    - subscribers
    - subscribe_nesting
    - publishers
    - advertise_nesting
    - active_publishers
    - publish_nesting
    - service_servers
    - advertise_service_nesting
    - service_clients
    - service_client_nesting
    - queue_size
    - hardcoded_topics
    - hardcoded_services
    - hardcoded_queue_sizes
    - hardcoded_spin_rates
    - latching_topics
    - infinite_queues
    - transport_hints
    - global_resource_names
    - function_callbacks
    - method_callbacks
    - boost_callbacks