%YAML 1.1
#Copyright (c) 2016 Andre Santos
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:

#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.
---
name: haros_plugin_radon
version: 0.1
languages:
    - python
rules: {}
metrics: {}
supported_rules:
    - max_file_length_400
    - min_comment_ratio_20
    - max_comment_ratio_30
    - max_comment_ratio_40
    - halstead_volume_above_8000
    - halstead_bugs_above_2
    - mi_below_20
    - mi_below_65
    - max_cyclomatic_complexity_10
    - max_cyclomatic_complexity_15
supported_metrics:
    - comments
    - comment_ratio
    - cyclomatic_complexity
    - halstead_bugs
    - halstead_time
    - halstead_volume
    - lloc
    - locom
    - maintainability_index
    - ploc
    - sloc