%YAML 1.1
---
name: dummy
version: 0.1
languages:
    - cpp
rules:
    roscpp_4.3:
        scope: file
        description:
            All files are under_scored.
            Source files have the extension .cpp.
            Header files have the extension .h.
        tags:
            - code-standards
            - roscpp
            - naming
metrics:
    ros_3.1:
        scope: file
        name: Comment to Code Ratio
        description: Comment to Code Ratio
        min: 0.2
supported_rules:
    - roscpp_4.3
supported_metrics:
    - ros_3.1