%YAML 1.1
---
name: radon_plugin
version: 0.1
languages:
    - python
rules: {}
metrics: {}
supported_rules:
    - max_function_length_40
    - min_comment_ratio_20
    - max_comment_ratio_30
    - max_comment_ratio_40
supported_metrics:
    - comment_ratio
    - cyclomatic_complexity
    - halstead_bugs
    - halstead_time
    - halstead_volume
    - lloc
    - locom
    - maintainability_index
    - ploc
    - sloc