%YAML 1.1
---
name: radon_plugin
version: 0.1
languages:
    - python
rules: {}
metrics: {}
supported_rules: []
supported_metrics:
    - comment_ratio
    - cyclomatic_complexity
    - halstead_bugs
    - halstead_time
    - halstead_volume
    - lloc
    - locom
    - maintainability_index
    - ploc
    - sloc