%YAML 1.1
---
name: radon_plugin
version: 0.1
languages:
    - python
rules: {}
metrics: {}
supported_rules:
    - max_file_length_400
    - min_comment_ratio_20
    - max_comment_ratio_30
    - max_comment_ratio_40
    - halstead_volume_above_8000
    - halstead_bugs_above_2
    - mi_below_20
    - mi_below_65
    - max_cyclomatic_complexity_10
    - max_cyclomatic_complexity_15
supported_metrics:
    - comment_ratio
    - cyclomatic_complexity
    - halstead_bugs
    - halstead_time
    - halstead_volume
    - lloc
    - locom
    - maintainability_index
    - ploc
    - sloc