%YAML 1.1
#Copyright (c) 2017 Andre Santos
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:

#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.

# This plugin requires pylint
# > pip install pylint
---
name: haros_plugin_pylint
version: 0.1
languages:
    - python
rules:
    refactor:
        name:           Pylint Refactor Rule
        scope:          file
        description:    Refactor for a 'good practice' metric violation.
        tags:
            - code-standards
            - pylint
    convention:
        name:           Pylint Convention Rule
        scope:          file
        description:    Convention for coding standard violation.
        tags:
            - code-standards
            - pylint
    warning:
        name:           Pylint Warning Rule
        scope:          file
        description:    Warning for stylistic problems, or minor programming issues.
        tags:
            - code-standards
            - pylint
    error:
        name:           Pylint Error Rule
        scope:          file
        description:    Error for important programming issues (i.e. most probably bug).
        tags:
            - code-standards
            - pylint
    fatal:
        name:           Pylint Fatal Rule
        scope:          file
        description:    Fatal for errors which prevented further processing.
        tags:
            - code-standards
            - pylint
supported_rules: []
