%YAML 1.1
#Copyright (c) 2018 Andre Santos
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:

#The above copyright notice and this permission notice shall be included in
#all copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#THE SOFTWARE.
---
name: haros_plugin_cccc
version: 0.1.1
languages:
    - cpp
depends:
    - cccc
metrics:
    fan_in:
        name: Fan-in
        scope: function
        description: "The fan-in is the number of other modules which use a given module."
        minimum: 0
    fan_out:
        name: Fan-out
        scope: function
        description: "The fan-out is the number of other modules which a given module uses."
        minimum: 0
    depth_of_inheritance_tree:
        name: Depth of Inheritance Tree
        scope: class
        description: "Depth of inheritance, also called depth of inheritance tree (DIT), is defined as the maximum length from the node to the root of the tree."
        minimum: 0
supported_metrics:
    - ploc
    - cyclomatic_complexity
    - comment_ratio
    - comments
