%YAML 1.1
---
name: lizard_plugin
version: 0.1
languages:
    - cpp
    - java
    - python
supported_rules:
    - max_function_parameters_6
    - max_cyclomatic_complexity_10
    - max_cyclomatic_complexity_15
supported_metrics:
    - cyclomatic_complexity
    - function_parameters
    - ploc